# Site
name: "HarmonyMotion"
title: "HarmonyMotion"
description: "Writer and 3D artist for hire"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: 'https://harmonymotion.com'
google_analytics: 'G-L8C49BJVGE'
#disqus: ''
#mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Harmo:
    name: HarmonyMotion
    display_name: HarmonyMotion
    avatar: 'assets/images/logo_hq.png'
    email: harmonymotionfiction@gmail.com
    web: https://www.deviantart.com/harmonymotion
  #  twitter: https://twitter.com/wowthemesnet
    description: ""

defaults:
  - scope:
      path: "portfolio/gallery"
    values:
      image: true

collections:
  stories: 
    output: true

pagination:
  enabled: true
  collection: 'stories'
  per_page: 10
  permalink: '/library/:num'
  limit: 0
  sort_field: 'publication-date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  trail:
    before: 2
    after: 2

# For story categories
category-list: [Superpowers, Omnipotent, Giantess, Mind Control, Attribute Theft, SSU, Cirraneverse]

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
# paginate: 6
# paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
